name: Docker Build (Next-Gen)

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
    
env:
  UBUNTU_VERSION: 24.04
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  cpu-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # This is not as silly as it seems... We will build for ARM later and this will be useful
        build:
          - {latest: "false"}
      
    steps:
      -
        name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      -
        name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}"
          base_tag="v3-cpu-ubuntu${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu" 
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest-cpu"
          else  
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: build
          build-args: |
            IMAGE_BASE=ubuntu:${{ env.UBUNTU_VERSION }}
            XPU_TARGET=CPU
          push: true
          # Avoids unknown/unknown architecture and extra metadata
          provenance: false
          tags: ${{ env.TAGS }}
    
  nvidia-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # The new, modernized NVIDIA build matrix for Ubuntu 24.04
        build:
        - {latest: "false",  cuda: "12.8.1-base"}
        - {latest: "false", cuda: "12.8.1-runtime"}
        - {latest: "false", cuda: "12.8.1-devel"}
        - {latest: "false", cuda: "12.5.1-base"}
        - {latest: "false", cuda: "12.5.1-runtime"}
        - {latest: "false", cuda: "12.5.1-devel"}
    
    steps:
      -
        name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      -
        name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}"
          
          base_tag="v3-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cuda"
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest-cuda"
          else  
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: build
          build-args: |
            IMAGE_BASE=nvidia/cuda:${{ matrix.build.cuda }}-ubuntu${{ env.UBUNTU_VERSION }}
            XPU_TARGET=NVIDIA_GPU
            CUDA_STRING=${{ matrix.build.cuda }}
          push: true
          provenance: false
          tags: ${{ env.TAGS }}

  amd-base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # The new, modernized ROCm build matrix for Ubuntu 24.04
        # NOTE: Official ROCm support for 24.04 may lag, we are being forward-looking here.
        build:
        - {latest: "false", rocm: "6.2-core"}
        - {latest: "false", rocm: "6.2-runtime"}
        - {latest: "false", rocm: "6.2-devel"}
        - {latest: "false", rocm: "6.1-core"}
        - {latest: "false", rocm: "6.1-runtime"}
        - {latest: "false", rocm: "6.1-devel"}
        #- {latest: "false", rocm: "6.0-core"}
        #- {latest: "false", rocm: "6.0-runtime"}
        #- {latest: "false", rocm: "6.0-devel"}

    steps:
      -
        name: Free Space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      -
        name: Env Setter
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          echo "REPO_NAMESPACE=${REPO%%/*}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO#*/}" >> ${GITHUB_ENV}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Permissions fixes
        run: |
          target="${HOME}/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/build/COPY*"
          chmod -R ug+rwX ${target}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set tags
        run: |
          img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
          img_path_dhub="${{ secrets.DOCKERHUB_USER }}/${{ env.REPO_NAME }}"
          base_tag="v3-rocm-${{ matrix.build.rocm }}-ubuntu${{ env.UBUNTU_VERSION }}"

          if [[ ${{ matrix.build.latest }} == "true" ]]; then
              echo "Marking latest"
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
              TAGS="${TAGS}, ${img_path_dhub}:${base_tag}, ${img_path_dhub}:latest-rocm"
          else
              TAGS="${img_path_ghcr}:${base_tag}, ${img_path_dhub}:${base_tag}"
          fi
          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: build
          build-args: |
            # Using rocm/dev-ubuntu-22.04 as base until 24.04 is officially supported
            # We will need to adapt the amd.sh script significantly.
            IMAGE_BASE=rocm/dev-ubuntu-22.04
            XPU_TARGET=AMD_GPU
            ROCM_STRING=${{ matrix.build.rocm }}
          push: true
          provenance: false
          tags: ${{ env.TAGS }}